services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PWD}:/srv/jekyll
    ports:
      - "${JEKYLL_PORT}:4000"
    command: bundle exec jekyll serve --host 0.0.0.0 --watch --force_polling